[Settings]

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.16.0"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      base-uri 'self';
      connect-src 'self' vitals.vercel-insights.com;
      default-src 'none';
      font-src 'self';
      form-action 'self';
      frame-ancestors 'none';
      frame-src 'self';
      img-src 'self';
      manifest-src 'self';
      media-src 'self';
      object-src 'none';
      script-src 'unsafe-inline' 'self' cdn.jsdelivr.net vitals.vercel-insights.com;
      style-src 'unsafe-inline' 'self' cdn.jsdelivr.net;
      upgrade-insecure-requests;
      """
    Permissions-Policy = "geolocation=(self), microphone=(self), camera=(self), fullscreen=(self)"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31557600; includesubdomains; preload"
    Vary = "Accept-Encoding"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
