name: 'ci(github): pr labels'
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        node-version: [20]
    name: 'ci(github): pr labels'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run PR Labeler
        uses: actions/labeler@v4
        with:
          configuration-path: .github/prlabels.yml
          sync-labels: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
