name: 'ci(github): pr labels'

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    name: 'ci(github): pr labels'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run PR Labeler
        uses: actions/labeler@v4
        with:
          configuration-path: .github/prlabels.yml
          sync-labels: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
