name: 'ci(github): release'
on:
  push:
    branches:
      - main
jobs:
  release:
    strategy:
      matrix:
        node-version: [20]
    name: 'ci(github): release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Log request details
        run: |
          console.log("Request Headers:", JSON.stringify(request.headers, null, 2));
          console.log("Request Body:", JSON.stringify(request.body, null, 2));
          console.log("Calculated Content-Length:", Buffer.byteLength(JSON.stringify(request.body), 'utf8'));
      - name: Run semantic-release
        id: semantic
        run: |
          OUTPUT=$(npx semantic-release) 
          if [[ $? -eq 0 ]]; then 
            echo "made_release=true" >> $GITHUB_ENV
          else 
            echo "made_release=false" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Format CHANGELOG.md with Prettier
        if: env.made_release == 'true'
        run: npx prettier --write CHANGELOG.md
      - name: Commit and push formatted CHANGELOG.md
        if: env.made_release == 'true'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@users.noreply.github.com"
          git add CHANGELOG.md
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "style(changelog): format CHANGELOG.md"
            git push
          fi
